### ISSUE TITLE
Unable to start the app

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Warehouse#6]
I am trying to start the Warehouse application and getting this error:

```
"System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Starcounter.Hosting.PrivateAssemblyStore.RegisterApplicationDirectory(DirectoryInfo dir) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-173\Level1\src\Hosting\Starcounter.Hosting\PrivateAssemblyStore.cs:line 54
   at StarcounterInternal.Hosting.Loader.ExecuteApplication(Void* hsched, ApplicationBase appBase, Boolean execEntryPointSynchronously, Stopwatch stopwatch) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-173\Level1\src\Hosting\Starcounter.Hosting\Loader.cs:line 153
   at Starcounter.Bootstrap.Management.ExecutablesHandler.OnPOST(Request request) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-173\Level1\src\Starcounter.Bootstrap\Management\ExecutablesHandler.cs:line 56
HResult=-2147467261
"
```

```
"ScErrServerCommandFailed (SCERR10011): The operation ""Starting Warehouse in default"" failed.
Version: 2.1.1154.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10011."
```

```
"Starcounter.DbException: ScErrDatabaseEngineTerminated (SCERR10007): The server detected that the user code host executable (sccode.exe) unexpectedly terminated during a management operation. , PID=668, Database=default
Version: 2.1.1154.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10007.
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.<>c__DisplayClass4_0.<Execute>b__3(CommandTask task) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-173\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 180
   at Starcounter.Server.Commands.CommandProcessor.<>c__DisplayClass68_0.<WithinTask>b__0(CommandTask t) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-173\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 484
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-173\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 510
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.Execute() in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-173\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 194
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\TeamCity\TeamCity9\buildAgent\work\sc-develop-nightly-173\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
ErrorCode=10007
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR10007
---> Starcounter.DbException: ScErrProcessExitCodeNotAvailable (SCERR10040): The exit code of the terminating process was not available.
Version: 2.1.1154.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR10040.
ErrorCode=10040
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR10040
"
```

What this could mean?

Starcounter version: `2.1.1154`.

**Comment by andwah** [comment]
cc @per-samuelsson, cc @alemoi , cc @chrhol

**Comment by miyconst** [comment]
Closing the issue as non-reproducible.

The issue has gone after I removed all Starcuonter files and reinstalled Starcounter.
